### PR TITLE
Login Fix

### PR DESCRIPTION
**Pull request by MauroGuerrero20**
# Bug Fixes
- Fixes not being able to logout or sign in properly when a user token expires.

### CODE REVIEW

**Review by steven-solar — APPROVED** [review]
Nice fix!

**Review by antoniolinhart — APPROVED** [review]
Nice easy fix!

**Review by VivekShankar — APPROVED** [review]
LGTM - nice, quick fix!

**Review by geoffbass — APPROVED** [review]
LGTM

**Pull request merged**
