### PR TITLE
Updating Favicon

### PR DESCRIPTION
**Pull request by antoniolinhart**
Adding new book favicon to the index.html

New Book Favicon

### CODE REVIEW

**Review by steven-solar — APPROVED** [review]
Looks great! Nice job designing this.

**Review by VivekShankar — APPROVED** [review]
Awesome, I love the design!

**Review by MauroGuerrero20 — APPROVED** [review]
LGTM

**Review by geoffbass — APPROVED** [review]
Nice! LGTM

**Pull request merged**
